### PR TITLE
Add fix to divertex fit, and update base branch to 10_6_22

### PR DESCRIPTION
**Pull request by steggema**
Main change is https://github.com/cms-hnl/cmssw/commit/c2cf36d5effc3c1e7f07f39ff06f15b1ddbc66d7

### CODE REVIEW

**Comment by kandrosov** [comment]
Just for my understanding: in which use cases we are still using 10_6_X?

**Comment by steggema** [comment]
I was using it so far for UL analysis and NanoAOD production, following https://twiki.cern.ch/twiki/bin/view/CMS/PdmVRun2LegacyAnalysis
Which release should we use instead?

**Comment by kandrosov** [comment]
for UL Nano production we using v10-like setup with 12_6

**Comment by kandrosov** [comment]
sorry I meant 12_4

**Comment by steggema** [comment]
should we then update the base branch here? https://github.com/cms-hnl/HNL/blame/master/README.md#L13-L19 or in other words, where do we document with branch we're currently using?

**Comment by kandrosov** [comment]
we have this section in Readme https://github.com/cms-hnl/HNL#how-to-run-miniaod-nanoaod-skims-production on how to setup&run things. I think previous readme sections should be considered as obsolete and can be removed...

**Comment by steggema** [comment]
ok got it, and agreed we should remove it since it can be confusing - do we also have instructions for condor?

**Comment by kandrosov** [comment]
> do we also have instructions for condor?

working on it (together with improved crab submission). ETA for the corresponding PR: end of the week.

**Comment by steggema** [comment]
ok great! will then close this PR and delete the obsolete branch

**Pull request closed without merging**
